server:
  port: 9000

eureka:
  client:
    register-with-eureka: true  # Service A will register itself with Eureka
    fetch-registry: true  # Service A will fetch the registry of other services from Eureka
    service-url:
      defaultZone: http://localhost:5000/eureka/

  instance:
    metadata-map:
      configPath: /app/portfolio/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: Portfolio App
    description: Portfolio microservice application
    version: 1.0.0

spring:
  application:
    name: portfolio-service

  datasource:
    url: jdbc:mysql://localhost:3306/hcl_microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Default Hibernate strategy
    show-sql: true
